server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 # 连接超时时间，单位为毫秒，默认30秒
      maximum-pool-size: 50 # 最大连接池大小，默认10
      minimum-idle: 25 # 最小空闲连接数，默认为maximum-pool-size的一半
      max-lifetime: 1800000 # 连接的最大存活时间，单位为毫秒，默认1800秒（30分钟）
      idle-timeout: 600000 # 连接的空闲超时时间，单位为毫秒，默认10分钟
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    root: info
    com.fuyuki.backend: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
